apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deploy
  labels:
    name: pg-deploy
    app: demo-voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
        name: pg-pod
        app: demo-voting-app
  template:
    metadata:
      name: pg-pod
      labels:
        name: pg-pod
        app: demo-voting-app
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
        env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"

