apiVersion: v1
kind: Pod
metadata:
  name: pg-pod
  labels:
    name: pg-pod
    app: demo-voting-app
spec:
  containers:
  - name: postgres
    image: postgres
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    ports:
      - containerPort: 5432
    env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
