apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app
    app: demo-voting-app
spec:
  type: NodePort
  selector:
    app: demo-voting-app
    name: votingapp-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
